import React, { useCallback, useEffect, useState } from 'react';
import { FilePlus2, Search, Sparkles, Trash2, Pencil, ClipboardList } from 'lucide-react';
import toast from 'react-hot-toast';
import { examQuestionsApi, examSetsApi } from '../../api';
import { useAuth } from '../../hooks/useAuth';
import { Badge, ConfirmDialog, EmptyState, Loading, Modal, StatusBadge } from '../../components/common';

const FORMAT_META: Record<string, { label: string; examType: string; duration: number; oneWay?: boolean; desc: string }> = {
  TOEIC_LR: { label: 'TOEIC hai kỹ năng', examType: 'TOEIC', duration: 120, desc: 'Listening 45 phút / 100 câu, Reading 75 phút / 100 câu' },
  TOEIC_4_SKILLS: { label: 'TOEIC bốn kỹ năng', examType: 'TOEIC', duration: 200, desc: 'Listening/Reading 120 phút, Speaking khoảng 20 phút, Writing 60 phút; tổng 200 phút / 219 câu-task' },
  VSTEP_4_SKILLS: { label: 'VSTEP bốn kỹ năng', examType: 'VSTEP', duration: 172, oneWay: true, desc: 'Listening 40 phút, Reading 60 phút, Writing 60 phút, Speaking 12 phút; chấm 4 kỹ năng thang 10' },
};

function ExamSetForm({ initial, onClose, onSuccess }: { initial?: any; onClose: () => void; onSuccess: () => void }) {
  const [questions, setQuestions] = useState<any[]>([]);
  const initialFormat = initial?.format_code || 'TOEIC_LR';
  const [form, setForm] = useState<any>({ title: initial?.title || '', formatCode: initialFormat, examType: FORMAT_META[initialFormat]?.examType || 'TOEIC', description: initial?.description || '', durationMinutes: initial?.duration_minutes || FORMAT_META[initialFormat]?.duration || 120, totalScore: initial?.total_score || 100, status: initial?.status || 'draft', settings: initial?.settings || { oneWayNavigation: !!FORMAT_META[initialFormat]?.oneWay }, questionIds: initial?.questions?.map((q: any) => q.id) || [] });
  useEffect(() => { examQuestionsApi.getAll({ formatCode: form.formatCode, status: 'active', limit: 300 }).then(res => setQuestions(res.data.questions || [])); }, [form.formatCode]);
  const submit = async () => {
    if (!form.title.trim()) return toast.error('Vui lòng nhập tên bộ đề');
    try { if (initial) await examSetsApi.update(initial.id, form); else await examSetsApi.create(form); toast.success('Đã lưu bộ đề'); onSuccess(); onClose(); }
    catch (err: any) { toast.error(err.response?.data?.message || 'Có lỗi xảy ra'); }
  };
  return <Modal title={initial ? 'Sửa bộ đề' : 'Tạo bộ đề thủ công'} size="lg" onClose={onClose} footer={<><button className="btn btn-secondary" onClick={onClose}>Huỷ</button><button className="btn btn-primary" onClick={submit}>Lưu</button></>}>
    <div className="grid-2"><div className="form-group" style={{ gridColumn: '1/-1' }}><label className="form-label">Tên bộ đề <span className="required">*</span></label><input className="form-input" value={form.title} onChange={e => setForm((f: any) => ({ ...f, title: e.target.value }))} /></div><div className="form-group"><label className="form-label">Format đề</label><select className="form-select" value={form.formatCode} onChange={e => { const meta = FORMAT_META[e.target.value]; setForm((f: any) => ({ ...f, formatCode: e.target.value, examType: meta.examType, durationMinutes: meta.duration, settings: { ...f.settings, oneWayNavigation: !!meta.oneWay }, questionIds: [] })); }}>{Object.entries(FORMAT_META).map(([code, meta]) => <option key={code} value={code}>{meta.label}</option>)}</select><div style={{ color: 'var(--gray-500)', fontSize: 12, marginTop: 4 }}>{FORMAT_META[form.formatCode]?.desc}</div></div><div className="form-group"><label className="form-label">Thời gian phút</label><input type="number" className="form-input" value={form.durationMinutes} onChange={e => setForm((f: any) => ({ ...f, durationMinutes: Number(e.target.value) }))} /></div><div className="form-group"><label className="form-label">Tổng điểm</label><input type="number" className="form-input" value={form.totalScore} onChange={e => setForm((f: any) => ({ ...f, totalScore: Number(e.target.value) }))} /></div><div className="form-group"><label className="form-label">Trạng thái</label><select className="form-select" value={form.status} onChange={e => setForm((f: any) => ({ ...f, status: e.target.value }))}><option value="draft">Nháp</option><option value="active">Công bố</option><option value="inactive">Khoá</option><option value="archived">Lưu trữ</option></select></div><label style={{ display: 'flex', gap: 8, alignItems: 'center', gridColumn: '1/-1', padding: '8px 0' }}><input type="checkbox" checked={!!form.settings?.oneWayNavigation} onChange={e => setForm((f: any) => ({ ...f, settings: { ...f.settings, oneWayNavigation: e.target.checked } }))} /> Áp dụng khóa điều hướng giữa các phần thi {form.formatCode === 'VSTEP_4_SKILLS' ? '(khuyến nghị bật cho VSTEP)' : ''}</label><div className="form-group" style={{ gridColumn: '1/-1' }}><label className="form-label">Mô tả</label><textarea className="form-textarea" value={form.description} onChange={e => setForm((f: any) => ({ ...f, description: e.target.value }))} /></div></div>
    <div className="form-group"><label className="form-label">Chọn câu hỏi ({form.questionIds.length})</label><div className="table-container" style={{ maxHeight: 280, overflow: 'auto' }}><table><thead><tr><th></th><th>Câu hỏi</th><th>Kỹ năng</th><th>Part</th></tr></thead><tbody>{questions.map(q => <tr key={q.id}><td><input type="checkbox" checked={form.questionIds.includes(q.id)} onChange={e => setForm((f: any) => ({ ...f, questionIds: e.target.checked ? [...f.questionIds, q.id] : f.questionIds.filter((id: number) => id !== q.id) }))} /></td><td>{q.question_text}</td><td>{q.skill}</td><td>{q.part}</td></tr>)}</tbody></table></div></div>
  </Modal>;
}

function GenerateForm({ onClose, onSuccess }: { onClose: () => void; onSuccess: () => void }) {
  const [form, setForm] = useState({ title: '', formatCode: 'TOEIC_LR', durationMinutes: 120, totalScore: 100, description: '', settings: { oneWayNavigation: false } });
  const submit = async () => { if (!form.title.trim()) return toast.error('Vui lòng nhập tên bộ đề'); try { await examSetsApi.generate(form); toast.success('Đã tự động sinh bộ đề từ ngân hàng câu hỏi'); onSuccess(); onClose(); } catch (err: any) { toast.error(err.response?.data?.message || 'Không thể sinh đề'); } };
  return <Modal title="Tự động sinh bộ đề" onClose={onClose} footer={<><button className="btn btn-secondary" onClick={onClose}>Huỷ</button><button className="btn btn-primary" onClick={submit}><Sparkles size={14}/> Sinh đề</button></>}>
    <div className="form-group"><label className="form-label">Tên bộ đề</label><input className="form-input" value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} /></div><div className="grid-2"><div className="form-group"><label className="form-label">Format đề</label><select className="form-select" value={form.formatCode} onChange={e => { const meta = FORMAT_META[e.target.value]; setForm(f => ({ ...f, formatCode: e.target.value, durationMinutes: meta.duration, settings: { oneWayNavigation: !!meta.oneWay } })); }}>{Object.entries(FORMAT_META).map(([code, meta]) => <option key={code} value={code}>{meta.label}</option>)}</select></div><div className="form-group"><label className="form-label">Thời gian phút</label><input type="number" className="form-input" value={form.durationMinutes} onChange={e => setForm(f => ({ ...f, durationMinutes: Number(e.target.value) }))} /></div></div><p style={{ color: 'var(--gray-500)', fontSize: 13 }}>Hệ thống sinh đề theo blueprint TOEIC/VSTEP. VSTEP mặc định bật khóa điều hướng một chiều và chấm 4 kỹ năng độc lập thang 10. Nếu ngân hàng chưa đủ câu, bộ đề vẫn được tạo với số câu hiện có.</p>
  </Modal>;
}

export default function ExamSetsPage() {
  const { user } = useAuth();
  const canDelete = user?.roles?.includes('admin');
  const [rows, setRows] = useState<any[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [formatCode, setFormatCode] = useState(''); const [showAdd, setShowAdd] = useState(false); const [showGenerate, setShowGenerate] = useState(false); const [editing, setEditing] = useState<any>(null); const [deleting, setDeleting] = useState<any>(null);
  const load = useCallback(async () => { setLoading(true); try { const res = await examSetsApi.getAll({ search, formatCode }); setRows(res.data.examSets || []); setTotal(res.data.total || 0); } finally { setLoading(false); } }, [search, formatCode]);
  useEffect(() => { load(); }, [load]);
  const edit = async (row: any) => { const res = await examSetsApi.getById(row.id); setEditing(res.data); };
  const del = async () => { await examSetsApi.delete(deleting.id); toast.success('Đã xoá bộ đề'); setDeleting(null); load(); };
  return <div><div className="page-header flex items-center justify-between"><div><h1 className="page-title">Bộ đề thi</h1><p className="page-subtitle">Tạo bộ đề TOEIC hoặc VSTEP; hỗ trợ checkbox khóa điều hướng giữa các kỹ năng</p></div><div style={{ display: 'flex', gap: 8 }}><button className="btn btn-secondary" onClick={() => setShowGenerate(true)}><Sparkles size={15}/> Sinh tự động</button><button className="btn btn-primary" onClick={() => setShowAdd(true)}><FilePlus2 size={15}/> Tạo bộ đề</button></div></div><div className="stats-grid"><div className="stat-card"><div><div className="stat-value">{total}</div><div className="stat-label">BỘ ĐỀ</div></div><ClipboardList color="var(--primary)" /></div></div><div className="filter-bar"><div className="search-input"><Search className="search-icon" size={14}/><input className="form-input" placeholder="Tìm tên bộ đề..." value={search} onChange={e => setSearch(e.target.value)} /></div><select className="form-select" style={{ width: 150 }} value={formatCode} onChange={e => setFormatCode(e.target.value)}><option value="">Tất cả</option><option value="TOEIC_LR">TOEIC hai kỹ năng</option><option value="TOEIC_4_SKILLS">TOEIC bốn kỹ năng</option><option value="VSTEP_4_SKILLS">VSTEP bốn kỹ năng</option></select></div>{loading ? <Loading /> : <div className="table-container"><table><thead><tr><th>Tên bộ đề</th><th>Loại</th><th>Số câu</th><th>Thời gian</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={6}><EmptyState /></td></tr> : rows.map(r => <tr key={r.id}><td><b>{r.title}</b><div style={{ color: 'var(--gray-500)', fontSize: 12 }}>{r.description}</div></td><td><Badge variant={r.exam_type === 'TOEIC' ? 'blue' : 'purple'}>{r.format_code || r.exam_type}</Badge></td><td>{r.question_count}</td><td>{r.duration_minutes} phút</td><td><StatusBadge status={r.status} /></td><td><div style={{ display: 'flex', gap: 6 }}><button className="btn btn-secondary btn-sm" onClick={() => edit(r)}><Pencil size={12}/> Sửa</button>{canDelete && <button className="btn btn-danger btn-sm" onClick={() => setDeleting(r)}><Trash2 size={12}/> Xoá</button>}</div></td></tr>)}</tbody></table></div>}{showAdd && <ExamSetForm onClose={() => setShowAdd(false)} onSuccess={load} />}{showGenerate && <GenerateForm onClose={() => setShowGenerate(false)} onSuccess={load} />}{editing && <ExamSetForm initial={editing} onClose={() => setEditing(null)} onSuccess={load} />}{deleting && <ConfirmDialog message={`Xoá bộ đề "${deleting.title}"?`} onCancel={() => setDeleting(null)} onConfirm={del} />}</div>;
}
